config/routes.rb
Rails.application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "Administrator" => "admins#index", :as => "Administrator"
  resources :users
  resources :categories
  resources :sessions
  resources :products do
   post :update_row_product, on: :collection
  end
   resources :products do
    collection do
      post :import
      get :autocomplete 
    end
  end
  match "admins/to_visible/:id" => "admins#to_visible",via: [:get, :post]
  match "admins/to_invisible/:id" => "admins#to_invisible",via: [:get, :post]
  root 'products#index'

end

app/views/layouts/_header.html.haml
#user_nav
  = link_to "Accueil", root_url
  - if current_user
    \#{link_to "Déconnexion", log_out_path} 
    = link_to "Gestion du catalogue", {:controller => "admins", :action => "index"} 
    = link_to "Enregistrer un autre admin", sign_up_path
  - else
    \#{link_to "Administrateur", log_in_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ecom
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash#{name}"
    = yield